CREATE TABLE public.plant (
    id                  int             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kor_name            text            NOT NULL UNIQUE,
    created_at          timestamp       NOT NULL
);