ALTER TABLE swear DROP CONSTRAINT "PK_SWEAR";

ALTER TABLE swear DROP COLUMN uuid;

ALTER TABLE swear ADD COLUMN id SERIAL;

ALTER TABLE ONLY public.swear
    ADD CONSTRAINT "PK_SWEAR" PRIMARY KEY (id);