ALTER TABLE public.comm_notification DROP CONSTRAINT "CHK_COMM_NOTIFICATION_ACTION";
ALTER TABLE public.comm_notification DROP CONSTRAINT "CHK_COMM_NOTIFICATION_STATUS";
ALTER TABLE public.comm_notification DROP CONSTRAINT "CHK_COMM_NOTIFICATION_COMMENT_PATH";