ALTER TABLE ONLY public.site_member_auth
    RENAME CONSTRAINT "UK_SITE_MEMBER_AUTH"
    TO "UK_SITE_MEMBER_AUTH_PROVIDER_ID";

ALTER TABLE ONLY public.site_member_auth
    ADD CONSTRAINT "UK_SITE_MEMBER_AUTH_EMAIL"
    UNIQUE (email);