# Apache Tomcat
server:
  tomcat:
    threads:
      max: 20
    max-connections: 100
    accept-count: 30

# Application
app:
  semaphore:
    datasource:
      allowed-connection-size: 12
      api: # 디폴트로 사용할 수 있는 최대 커넥션 수
        connection-size: 9
      bulkhead: # 벌크헤드 패턴으로 격리된 개별 기능에 사용하는 최대 커넥션 수
        notification:
          connection-size: 3

# Debugging & Logging
logging:
  level:
    root: DEBUG
    io.lettuce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
security:
  debug:
    enabled: true

# MinIO
minio:
  public-endpoint: ${DEV_PUBLIC_ENDPOINT}

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시
  notification-cleanup-cron : "0 10 3 * * *"

# Spring
spring:
  datasource:
    hikari:
      pool-name: DevHikariPool
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        show_sql: true

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Wasabi
cloud:
  wasabi:
    s3:
      max-connections: 6